version: "3.5"

services:
  postgres-db:
    image: "postgres:9.6-alpine"
    environment:
      - "POSTGRES_DB=demo"
      - "POSTGRES_USER=demo"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"

  mysql8-db:
    image: "mysql:8.0.19"
    environment:
      - "MYSQL_DATABASE=demo"
      - "MYSQL_USER=demo"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root_password"
    ports:
      - "3306:3306"
    volumes:
      - "mysql8-data:/var/lib/mysql"

  mysql5-db:
    image: "mysql:5.7"
    environment:
      - "MYSQL_DATABASE=demo"
      - "MYSQL_USER=demo"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root_password"
    ports:
      - "3306:3306"
    volumes:
      - "mysql5-data:/var/lib/mysql"

  mongo-db:
    image: "mongo:4.0.16-xenial"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=demo"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
      - "MONGO_INITDB_DATABASE=demo"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"

  mongo-express:
    image: "mongo-express:0.54"
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=demo"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=password"
      - "ME_CONFIG_MONGODB_SERVER=mongo-db"

  rabbitmq:
    image: "rabbitmq:3.8.2-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbit-data:/var/lib/rabbitmq"

  redis:
    image: "redis:6.0.8-alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

volumes:
  pg-data:
  mysql5-data:
  mysql8-data:
  mongo-data:
  rabbit-data:
  redis-data:
