version: "3.5"

services:
  postgres-db:
    image: "postgres:9.6-alpine"
    environment:
      - "POSTGRES_DB=demo"
      - "POSTGRES_USER=demo"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"

  mysql-db:
    image: "mysql:8.0.19"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_DATABASE=demo"
      - "MYSQL_USER=demo"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root_password"
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

  mongo-db:
    image: "mongo:4.0.16-xenial"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=demo"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"

  mongo-express:
    image: "mongo-express:0.54"
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=demo"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=password"
      - "ME_CONFIG_MONGODB_SERVER=mongo-db"

  rabbitmq:
    image: "rabbitmq:3.8.2-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbit-data:/var/lib/rabbitmq"

volumes:
  pg-data:
  mysql-data:
  mongo-data:
  rabbit-data:
