apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongo-express
  template:
    metadata:
      labels:
        component: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:0.54
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-cluster-ip-service
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: demo
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: password
