apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: whoami
  template:
    metadata:
      labels:
        component: whoami
    spec:
      containers:
        - name: whoami
          image: stefanscherer/whoami
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: whoami
  ports:
    - port: 8080
      targetPort: 8080
