version: "3.5"

services:
  traefik:
    image: "traefik:v2.3"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/traefik.toml:/etc/traefik/traefik.toml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.just4demo.live`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$ajo1qyZ0$$kHxoL6VpoxlrBafRHREjZ."

  whoami:
    image: "containous/whoami"
    ports:
      - "8000:80"
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.just4demo.live`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.enable=true
