defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]  
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "myresolver"
      [[entryPoints.websecure.http.tls.domains]]
        main = "*.just4demo.live"

[certificatesResolvers.myresolver.acme]
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  email = "thanhdao.junctionxhanoi@gmail.com"
  storage = "/acme.json"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
    provider = "namedotcom"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[api]
  dashboard = true

[log]
  level = "DEBUG"