apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: mongo
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongo
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.0.16-xenial
          env:
            - name: MONGO_INITDB_DATABASE
              value: demo
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001
