version: "3.5"

services:
  kong-database:
    image: "postgres:9.6-alpine"
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=kong"
      - "POSTGRES_USER=kong"
      - "POSTGRES_PASSWORD=password"

  kong:
    image: kong:latest
    restart: always
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kong-database"
      - "KONG_PG_PASSWORD=password"
